export const API_ROUTES = {
  // BASE_URL: "http://192.168.100.102:7930/api/",//(Q.A)
  BASE_URL: "http://192.168.100.102:7830/api/", //(development)
  // BASE_URL: "http://192.168.80.25:7930/api/",// (Nitesh Ip)
  // BASE_URL: "http://160.25.172.19:9052/api/", //Public Server
  AUTHORIZE_LOGIN: "userauth/authenticate/login",
  GET_PROFILE: "userauth/all/get-profile",
  PROFILE_DETAILS: "master/employee-master/find-by-id",
  PROGRAMME_LIST: "prod_plan/prd-schedule/find-by-filter",
  PROGRAMME_LIST_DETAILS: "prod_plan/prd-schedule/dd",
  GROWER_DETAILS: "master/parties-master/growers-filter/dd",
  PRODUCTION_INSPECTION_A: "prod_plan/prd-ins-type-a/find-by-filter",
  PRODUCTION_INSPECTION_B: "prod_plan/prd-ins-type-b/find-by-filter",
  PRODUCTION_INSPECTION_C: "prod_plan/prd-ins-type-c/find-by-filter",
  DOWNLOAD_PROGRAM_EXCEL_LIST: "prod_plan/prd-schedule/download-excel",
  SEEDS_INTAKE_HISTORY: "prod_plan/prd-sch-seed-intake/find-by-filter",
  CHANGE_PASSWORD: "userauth/public/user/changePassword",
  CROP_LIST: "master/crop-master/find-by-filter",
  SESSION_MASTER: "master/season-master/find-by-filter",
  CROP_FIR_MASTER: "master/crop-fir-types-master/find-by-filter",
  CROP_GROUP_MASTER: "master/crop-group-master/dd",
  ADD_CROP: "master/crop-master/save",
  UPDATE_CROP: "master/crop-master/update",
  INSPECTION_SAVE_A: "prod_plan/prd-ins-type-a/save",
  INSPECTION_SAVE_B: "prod_plan/prd-ins-type-b/save",
  INSPECTION_SAVE_C: "prod_plan/prd-ins-type-c/save",
  PRODUCTION_PLAN: "prod_plan/production-plan/find-by-filter",
  SEASON_MASTER_DD: "master/season-master/dd",
  FINANCIAL_MASTER_DD: "master/financial-year-master/dd",
  CROP_MASTER_DD: "master/crop-master/dd",
  SEED_VARIETY_MASTER: "master/seed-varieties-master/dd",
  DP_REPORT: "prod_plan/dp-report/find-by-filter",
  DP_REPORT_DETAILS: "prod_plan/dp-report/find-by-id",
  SQUARE_MASTER_DD: "master/square-master/dd",
  OPERATION_MASTER_DD: "master/operation-master/dd",
  MACHINE_MASTER_DD: "master/machine-master/dd",
  DP_REPORT_SAVE: "prod_plan/dp-report/save",
  DP_REPORT_UPDATE: "prod_plan/dp-report/update",
};
