export const ROLES = {
  // DPR
  CHAK: "CHAK_PROD_INCHARGE",
  BLOK: "FARM_BLOCK_PROD_INCHARGE",
  MECHANICAL_BLOCK_ENGG: "FARM_BLOCK_ENGG_INCHARGE",
  EPO_INCHARGE: "EPO_INCHARGE",

  // Dealer Indent
  AO_MKT_INCHARGE: "AO_MKT_INCHARGE",

  // Field inspection report
  AO_QC_INCHARGE: "AO_QC_INCHARGE",
};
