export default {
  noInternet: require("../assets/animation/noInternet.json"),
  rootedImage: require("../assets/image/rootedImage.png"),
  splashImage: require("../assets/image/splash.png"),
  logoImage: require("../assets/image/logo.png"),
  logoBgImage: require("../assets/image/loginBg.png"),
  emailIcon: require("../assets/image/email.png"),
  password: require("../assets/image/lock.png"),
  userProfile: require("../assets/image/userProfile.png"),
  notification: require("../assets/image/notification.png"),
  bannerImage: require("../assets/image/bannerImage.png"),
  complaint: require("../assets/image/complaint.png"),
  registrationIcon: require("../assets/image/registration.png"),
  forgotPasswordBackgroundImage: require("../assets/image/loginBgPattern.jpg"),
  nsclLogo: require("../assets/image/nsclLogo.png"),
};
